DROP TABLE IF EXISTS USER_TASK ;
CREATE TABLE `USER_TASK` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `NAME` VARCHAR(255) NOT NULL COMMENT '姓名',
  `STATUS` TINYINT DEFAULT NULL COMMENT '年龄',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;